<?php

/**
 * @file
 * Hooks for migrate_exmaple_i18n.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
// function pb_custom_migrate_migration_plugins_alter(array &$migrations) {
//   // For each 'example_element' migration, alter its 'source' so that it looks
//   // wherever this module was installed for CSV files.
//   foreach ($migrations as &$migration) {
//     if (in_array('element', $migration['migration_tags'])) {
//       $path =& $migration['source']['path'];
//       $path = drupal_get_path('module', 'pb_custom_migrate') .
//         '/import_files/' . $path;
//     }
//   }
// }
