language: php
sudo: false

php:
  - 7

env:
  global:
    # The name of the moduel to run tests on (this module).
    - DRUPAL_MODULE=json_field
    # Database variable for kernel tests.
    - SIMPLETEST_DB="mysql://root:@127.0.0.1/drupal"
    # Web server URL for browser tests.
    - SIMPLETEST_BASE_URL="http://localhost:8888"

matrix:
  # Don't wait for the allowed failures to build.
  fast_finish: true

services:
  - mysql

install:
  # Add composer's global bin directory to the path
  # See: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"

  # Install drush globally
  - composer global require drush/drush:^8.1.18

before_script:
  # Remove Xdebug as we don't need it and it causes
  - phpenv config-rm xdebug.ini || true

  # Create database.
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' -uroot

  # Set the drupal root folder location.
  - export DRUPAL_ROOT=$TRAVIS_BUILD_DIR/../drupal/web

  # Download Drupal 8 core.
  - composer create-project drupal-composer/drupal-project:8.x-dev $TRAVIS_BUILD_DIR/../drupal/ --no-interaction

  # Reference the module in build site.
  - ln -s $TRAVIS_BUILD_DIR $DRUPAL_ROOT/modules/$DRUPAL_MODULE

  # We need to run simpletest so install drupal and enable simpletest.
  - drush -y --root=$DRUPAL_ROOT site-install --db-url=$SIMPLETEST_DB
  - drush -y --root=$DRUPAL_ROOT en simpletest $DRUPAL_MODULE

  # Start a web server on port 8888, run in the background and wait.
  - php $DRUPAL_ROOT/core/scripts/drupal server -s -n --port=8888 > /dev/null 2>&1 &

script:
  # Run the tests.
  - $DRUPAL_ROOT/../vendor/bin/phpunit -c $DRUPAL_ROOT/core/phpunit.xml.dist --verbose $DRUPAL_ROOT/modules/$DRUPAL_MODULE
