adding:
  display:
    default:
      display_options:
        arguments:
          tltid:
            exception:
              title: All
removing:
  display:
    default:
      display_title: Master
      display_options:
        exposed_form:
          options:
            submit_button: Použiť
            exposed_sorts_label: 'Zoradiť podľa'
            sort_asc_label: Vzostupne
            sort_desc_label: Zostupne
        pager:
          options:
            expose:
              items_per_page_label: 'Položky na stránku'
              items_per_page_options_all_label: '- Všetky -'
              offset_label: Ofset
            tags:
              previous: '‹ Predchádzajúci'
              next: Ďalej
              first: «
              last: »
        fields:
          label:
            label: Označenie
          item_type:
            separator: ', '
          word_count:
            label: Slov
            separator: ', '
        arguments:
          tltid:
            exception:
              title: Všetko
    block_1:
      display_title: Blok
