version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - echo $IMAGE_NAME
      - echo $AWS_DEFAULT_REGION        
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest 817747646454.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 817747646454.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_NAME:latest