adding:
  status: true
  dependencies:
    config:
      - workflows.workflow.group_workflow
  display:
    default:
      display_options:
        filters:
          moderation_state:
            id: moderation_state
            table: node_field_data
            field: moderation_state
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            plugin_id: moderation_state_filter
            operator: in
            value:
              group_workflow-sme_review: group_workflow-sme_review
            group: 1
            exposed: false
            expose:
              operator_id: ''
              label: ''
              description: ''
              use_operator: false
              operator: ''
              operator_limit_selection: false
              operator_list: {  }
              identifier: ''
              required: false
              remember: false
              multiple: false
              remember_roles:
                authenticated: authenticated
              reduce: false
            is_grouped: false
            group_info:
              label: ''
              description: ''
              identifier: ''
              optional: true
              widget: select
              multiple: false
              remember: false
              default_group: All
              default_group_multiple: {  }
              group_items: {  }
removing:
  status: false
