adding:
  uuid: fed30a66-9a00-4559-a232-ae1ac2e425a2
  dependencies:
    module:
      - content_translation
  third_party_settings:
    content_translation:
      enabled: false
      bundle_settings:
        untranslatable_fields_hide: '0'
removing:
  uuid: 6c3277bc-3046-4e68-816b-14f7ec4c5e96
