adding:
  tags:
    abstract: 'Uygulama, Türkiye bağlamına göre uyarlanmıştır ve çocuklu ailelerin çeşitli konularda uzman tavsiyelerine erişmesine olanak sağlar.'
    description: 'Uygulama, Türkiye bağlamına göre uyarlanmıştır ve çocuklu ailelerin çeşitli konularda uzman tavsiyelerine erişmesine olanak sağlar.'
    keywords: 'beslenme, erken çocuk gelişimi, sağlık, Merhaba Bebek, ebeveynlik uygulaması, emzirme, aşılama, hamilelik'
removing:
  tags:
    abstract: "UNICEF’s parenting app Bebbo helps you answer questions about raising children, kid's nutrition and much more. Find out more and download it here."
    description: 'UNICEF’s parenting app Bebbo helps you answer questions about raising children, kids nutrition, early learning, health and wellbeing. Find out more and download it here.'
    keywords: "nutrition, early learning, health, wellbeing, Bebbo, parenting app, parent app, baby weaning, breast pump, nappy rash, baby milestone cards, learning toys for toddlers, early learning goals, baby weaning recipes, baby feeding bottle, feeding pillow, baby milestone blanket, colic calm, milk allergy in babies, child protection and safeguarding, parenting, parenting tips, child development, parenting advice, parenting games, kid's vaccinations, growth tracker, raising children"
