adding:
  dependencies:
    config:
      - workflows.workflow.group_workflow
  permissions:
    - 'use group_workflow transition archive_to_draft'
    - 'use group_workflow transition draft_to_senior_editor_review'
    - 'use group_workflow transition draft_to_sme_review'
    - 'use group_workflow transition publish_to_draft'
    - 'use group_workflow transition reject_to_draft'
    - 'use group_workflow transition review_after_translation_to_draft'
    - 'use group_workflow transition review_after_translation_to_review_after_translation'
    - 'use group_workflow transition review_after_translation_to_senior_editor_review'
    - 'use group_workflow transition review_after_translation_to_sme_review'
removing: {  }
