adding:
  status: true
  dependencies:
    config:
      - workflows.workflow.group_workflow
  display:
    page_4:
      display_options:
        filters:
          moderation_state:
            id: moderation_state
            table: node_field_data
            field: moderation_state
            relationship: none
            group_type: group
            admin_label: ''
            entity_type: node
            plugin_id: moderation_state_filter
            operator: in
            value:
              group_workflow-published: group_workflow-published
            group: 1
            exposed: false
            expose:
              operator_id: moderation_state_op
              label: 'Moderation state'
              description: null
              use_operator: false
              operator: moderation_state_op
              operator_limit_selection: false
              identifier: moderation_state
              required: false
              remember: false
              multiple: false
              remember_roles:
                authenticated: authenticated
              reduce: false
            is_grouped: false
            group_info:
              label: ''
              description: ''
              identifier: ''
              optional: true
              widget: select
              multiple: false
              remember: false
              default_group: All
removing:
  status: false
