warmers:
  cdn:
    id: cdn
    frequency: 3600
    batchSize: 10
    urls:
      - '/api/activities/en'
      - '/api/archive/en'
      - '/api/articles/en'
      - '/api/articles/en?pregnancy=true'
      - '/api/basic-pages/en'
      - '/api/child-development-data/en'
      - '/api/child-growth-data/en'
      - '/api/daily-homescreen-messages/en'
      - '/api/faqs/en'
      - '/api/health-checkup-data/en'
      - '/api/milestones/en'
      - '/api/pinned-contents/en/child_development/40'
      - '/api/pinned-contents/en/child_development/41'
      - '/api/pinned-contents/en/child_growth'
      - '/api/pinned-contents/en/faq'
      - '/api/pinned-contents/en/health_check_ups'
      - '/api/pinned-contents/en/vaccinations'
      - '/api/related-article-contents/en/milestone'
      - '/api/standard_deviation/en'
      - '/api/surveys/en'
      - '/api/taxonomies/en/all'
      - '/api/updated-pinned-contents/en/faq'
      - '/api/vaccinations/en'
      - '/api/video-articles/en'
      - '/api/activities/tr'
      - '/api/archive/tr'
      - '/api/articles/tr'
      - '/api/articles/tr?pregnancy=true'
      - '/api/basic-pages/tr'
      - '/api/child-development-data/tr'
      - '/api/child-growth-data/tr'
      - '/api/daily-homescreen-messages/tr'
      - '/api/faqs/tr'
      - '/api/health-checkup-data/tr'
      - '/api/milestones/tr'
      - '/api/pinned-contents/tr/child_development/40'
      - '/api/pinned-contents/tr/child_development/41'
      - '/api/pinned-contents/tr/child_growth'
      - '/api/pinned-contents/tr/faq'
      - '/api/pinned-contents/tr/health_check_ups'
      - '/api/pinned-contents/tr/vaccinations'
      - '/api/related-article-contents/tr/milestone'
      - '/api/standard_deviation/tr'
      - '/api/surveys/tr'
      - '/api/taxonomies/tr/all'
      - '/api/updated-pinned-contents/tr/faq'
      - '/api/vaccinations/tr'
      - '/api/video-articles/tr'
    headers: {  }
    verify: true
    maxConcurrentRequests: 2
