adding:
  display:
    default:
      display_options:
        cache:
          type: none
          options: {  }
        style:
          options:
            columns:
              views_bulk_operations_bulk_form: views_bulk_operations_bulk_form
              revision_uid: revision_uid
            info:
              views_bulk_operations_bulk_form:
                align: ''
                separator: ''
                empty_column: false
                responsive: ''
              revision_uid:
                sortable: false
                default_sort_order: asc
                align: ''
                separator: ''
                empty_column: false
                responsive: ''
removing:
  display:
    default:
      display_options:
        cache:
          type: tag
        style:
          options:
            columns:
              name: name
            info:
              name:
                sortable: true
                default_sort_order: asc
                align: ''
                separator: ''
                empty_column: false
                responsive: priority-low
    page_5:
      display_options:
        cache:
          type: none
        defaults:
          cache: false
