adding:
  display:
    default:
      display_options:
        style:
          options:
            columns:
              revision_uid: revision_uid
            info:
              revision_uid:
                sortable: false
                default_sort_order: asc
                align: ''
                separator: ''
                empty_column: false
                responsive: ''
            sticky: false
removing:
  display:
    default:
      display_options:
        style:
          options:
            columns:
              name: name
            info:
              name:
                sortable: true
                default_sort_order: asc
                align: ''
                separator: ''
                empty_column: false
                responsive: priority-low
            sticky: true
