appID: K288UMKCNF.org.unicef.zw.reraiumntwana
paths: '/share/*'
appclips: ''
appID_Test: K288UMKCNF.org.unicef.zw.reraiumntwana
paths_Test: '/share/*'
kosovo_appID: ''
kosovo_paths: ''
kosovo_appclips: ''
kosovo_appID_Test: ''
kosovo_paths_Test: ''
applinks:
  K288UMKCNF-org-unicef-zw-reraiumntwana_0:
    applinks: ''
    appID: K288UMKCNF.org.unicef.zw.reraiumntwana
    paths: '/share/*'
    appclips: ''
    appIDs: {  }
    defaults: ''
