landing_pages: |-
  /homepage
  /about-us
  /terms-and-conditions
  /privacy-policy
  /homepage/zw-sn
  /about-us/zw-sn
  /terms-and-conditions/zw-sn
  /privacy-policy/zw-sn
  /homepage/zw-nd
  /about-us/zw-nd
  /terms-and-conditions/zw-nd
  /privacy-policy/zw-nd