warmers:
  cdn:
    id: cdn
    frequency: 3600
    batchSize: 10
    urls:
      - '/api/activities/zw-en'
      - '/api/archive/zw-en'
      - '/api/articles/zw-en'
      - '/api/articles/zw-en?pregnancy=true'
      - '/api/basic-pages/zw-en'
      - '/api/child-development-data/zw-en'
      - '/api/child-growth-data/zw-en'
      - '/api/daily-homescreen-messages/zw-en'
      - '/api/faqs/zw-en'
      - '/api/health-checkup-data/zw-en'
      - '/api/milestones/zw-en'
      - '/api/pinned-contents/zw-en/child_development/40'
      - '/api/pinned-contents/zw-en/child_development/41'
      - '/api/pinned-contents/zw-en/child_growth'
      - '/api/pinned-contents/zw-en/faq'
      - '/api/pinned-contents/zw-en/health_check_ups'
      - '/api/pinned-contents/zw-en/vaccinations'
      - '/api/related-article-contents/zw-en/milestone'
      - '/api/standard_deviation/zw-en'
      - '/api/surveys/zw-en'
      - '/api/taxonomies/zw-en/all'
      - '/api/updated-pinned-contents/zw-en/faq'
      - '/api/vaccinations/zw-en'
      - '/api/video-articles/zw-en'
      - '/api/activities/zw-sn'
      - '/api/archive/zw-sn'
      - '/api/articles/zw-sn'
      - '/api/articles/zw-sn?pregnancy=true'
      - '/api/basic-pages/zw-sn'
      - '/api/child-development-data/zw-sn'
      - '/api/child-growth-data/zw-sn'
      - '/api/daily-homescreen-messages/zw-sn'
      - '/api/faqs/zw-sn'
      - '/api/health-checkup-data/zw-sn'
      - '/api/milestones/zw-sn'
      - '/api/pinned-contents/zw-sn/child_development/40'
      - '/api/pinned-contents/zw-sn/child_development/41'
      - '/api/pinned-contents/zw-sn/child_growth'
      - '/api/pinned-contents/zw-sn/faq'
      - '/api/pinned-contents/zw-sn/health_check_ups'
      - '/api/pinned-contents/zw-sn/vaccinations'
      - '/api/related-article-contents/zw-sn/milestone'
      - '/api/standard_deviation/zw-sn'
      - '/api/surveys/zw-sn'
      - '/api/taxonomies/zw-sn/all'
      - '/api/updated-pinned-contents/zw-sn/faq'
      - '/api/vaccinations/zw-sn'
      - '/api/video-articles/zw-sn'
      - '/api/activities/zw-nd'
      - '/api/archive/zw-nd'
      - '/api/articles/zw-nd'
      - '/api/articles/zw-nd?pregnancy=true'
      - '/api/basic-pages/zw-nd'
      - '/api/child-development-data/zw-nd'
      - '/api/child-growth-data/zw-nd'
      - '/api/daily-homescreen-messages/zw-nd'
      - '/api/faqs/zw-nd'
      - '/api/health-checkup-data/zw-nd'
      - '/api/milestones/zw-nd'
      - '/api/pinned-contents/zw-nd/child_development/40'
      - '/api/pinned-contents/zw-nd/child_development/41'
      - '/api/pinned-contents/zw-nd/child_growth'
      - '/api/pinned-contents/zw-nd/faq'
      - '/api/pinned-contents/zw-nd/health_check_ups'
      - '/api/pinned-contents/zw-nd/vaccinations'
      - '/api/related-article-contents/zw-nd/milestone'
      - '/api/standard_deviation/zw-nd'
      - '/api/surveys/zw-nd'
      - '/api/taxonomies/zw-nd/all'
      - '/api/updated-pinned-contents/zw-nd/faq'
      - '/api/vaccinations/zw-nd'
      - '/api/video-articles/zw-nd'
    headers:
      - 'X-Bebbo-Warmer: 1'
    verify: true
    maxConcurrentRequests: 8
