display:
  default:
    display_options:
      fields:
        edit_user:
          text: 'Edit member'
        name:
          label: User
        group_roles:
          label: Roles
        view_group_relationship:
          text: 'Manage member'
        edit_group_relationship:
          text: 'Assign roles'
        dropbutton:
          label: Operations
      pager:
        options:
          tags:
            previous: ‹‹
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
