display:
  default:
    display_title: Default
    display_options:
      fields:
        created:
          label: Created
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
