display:
  default:
    display_title: Default
    display_options:
      pager:
        options:
          tags:
            previous: ‹‹
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
