adding:
  label: 'Custom block library'
  description: 'Find and manage custom blocks.'
  display:
    default:
      display_options:
        title: 'Custom block library'
        exposed_form:
          options:
            reset_button_label: Reset
        empty:
          area_text_custom:
            content: 'There are no custom blocks available.'
    page_1:
      display_options:
        menu:
          description: 'Create and edit block content.'
removing:
  description: 'İçerik bloklarını bulun ve yönetin.'
  display:
    default:
      display_options:
        fields:
          info:
            label: 'Blok açıklaması'
            separator: ', '
          type:
            label: 'Blok tipi'
            separator: ', '
          changed:
            label: Güncellenme
        pager:
          options:
            tags:
              next: 'Sonraki ›'
              previous: '‹ Önceki'
            expose:
              items_per_page_label: 'Sayfa başına öğe sayısı'
              items_per_page_options_all_label: '- Tümü -'
              offset_label: 'Başlangıç değeri'
        exposed_form:
          options:
            submit_button: Uygula
            reset_button_label: Sıfırla
            exposed_sorts_label: 'Sıralama anahtarı'
            sort_asc_label: Artan
            sort_desc_label: Azalan
        empty:
          area_text_custom:
            content: 'Kullanılabilir içerik bloğu yok.'
        filters:
          info:
            expose:
              label: 'Blok açıklaması'
          type:
            expose:
              label: 'Blok tipi'
    page_1:
      display_title: Sayfa
