<?php

use Drupal\Core\Form\FormState;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\group\Entity\Group;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\language\Entity\ConfigurableLanguage;
use Drupal\languagefield\Entity;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\TypedData\OptionsProviderInterface;
use Drupal\Core\Language\LanguageManager;
use Drupal\views\Plugin\views\query\QueryPluginBase;
/**
 * @file
 * It contains custom field module.
 */

function group_country_field_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
if($form['#id'] == "views-exposed-form-content-listing-page-4")
  {

    $groups = Group::loadMultiple(); 
    // $gids = \Drupal::entityQuery('group')->condition('type','country')->execute();
    // $groups = \Drupal\group\Entity\Group::loadMultiple($gids);
    // dump($groups);
    // die();
    $options = ['' => 'All'];
    // echo "<pre>";
    // print_r($groups);

    foreach($groups as $gid => $group) {
      $value = $group->get('label')->getString();
      $id = $group->get('id')->getString();

      if (isset($value)) {
        //$options[strtolower($value)] = $value;
        $options[$id] = $value;
      }
    }
    //dump($form['gtitle']);
    if (isset($form['gtitle1'])) {
      $form['gtitle1']['#type'] = 'select';
      $form['gtitle1']['#options'] = $options;
      $form['gtitle1']['#size'] = 1;
      return $form;
    }
  }
}




