# Schema for the configuration files of the acquia_connector module.

acquia_connector.settings:
  type: config_object
  label: 'Acquia connector settings'
  mapping:
    debug:
      type: boolean
      label: 'Is debug mode active'
    cron_interval:
      type: integer
      label: 'Interval for sending site profile, minutes'
    cron_interval_override:
      type: integer
      label: 'Override for cron_interval, minutes'
    hide_signup_messages:
      type: integer
      label: 'Hide signup messages'
    third_party_settings:
      type: ignore
      label: 'Product specific settings'
