adding:
  display:
    default:
      display_options:
        fields:
          state:
            label: Статус
          label:
            label: Ознака
          operations:
            label: Операције
    checkout:
      display_options:
        fields:
          label:
            label: Ознака
removing:
  display:
    default:
      display_options:
        exposed_form:
          options:
            exposed_sorts_label: 'Sort by'
        fields:
          state:
            label: State
          label:
            label: Label
          operations:
            label: Operations
    checkout:
      display_options:
        fields:
          label:
            label: Label
