languagefield.custom_language.*:
  type: config_entity
  label: 'Custom language'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    direction:
      type: string
      label: 'Direction'
    weight:
      type: integer
      label: 'Weight'
    native_name:
      type: string
      label: 'Native name'

field.field_settings.languagefield:
  type: mapping
  label: 'Custom language field settings'
  mapping:
    maxlength:
      type: string
      label: 'Size'
    language_range:
       type: array
       label: 'Enabled languages'
    included_languages:
       type: array
       label: 'Included languages'
    excluded_languages:
       type: array
       label: 'Excluded languages'
    groups:
       type: array
       label: 'Language groups'
    allowed_values_function:
      type: string
      label: 'allowed_values_function'
