adding:
  display:
    default:
      display_options:
        exposed_form:
          options:
            reset_button_label: Reset
    page:
      display_options:
        fields:
          delete_media:
            text: Delete
    widget:
      display_options:
        arguments:
          bundle:
            exception:
              title: All
    widget_table:
      display_options:
        arguments:
          bundle:
            exception:
              title: All
removing:
  display:
    default:
      display_options:
        title: Medya
        fields:
          media_bulk_form:
            action_title: Eylem
        pager:
          options:
            tags:
              next: ››
              previous: ‹‹
            expose:
              items_per_page_label: 'Sayfa başına öğe sayısı'
              items_per_page_options_all_label: '- Tümü -'
              offset_label: 'Başlangıç değeri'
        exposed_form:
          options:
            submit_button: 'Filtreleri uygula'
            reset_button_label: Sıfırla
            exposed_sorts_label: 'Sıralama anahtarı'
            sort_asc_label: Artan
            sort_desc_label: Azalan
        empty:
          area_text_custom:
            content: 'Ortam yok.'
        sorts:
          created:
            expose:
              label: 'Önce en yeniler'
          name:
            expose:
              label: 'Ad (A-Z)'
          name_1:
            expose:
              label: 'Ad (Z-A)'
        filters:
          status:
            expose:
              label: 'Yayımlanma durumu'
            group_info:
              label: Yayında
              group_items:
                1:
                  title: Yayında
                2:
                  title: 'Yayında değil'
          bundle:
            expose:
              label: 'Medya tipi'
            group_info:
              label: 'Medya tipi'
    page:
      display_title: Sayfa
      display_options:
        fields:
          media_bulk_form:
            action_title: Eylem
          name:
            separator: ', '
          edit_media:
            text: Düzenle
          delete_media:
            text: Sil
    widget:
      display_title: 'Arayüz kontrolü (widget)'
      display_options:
        arguments:
          bundle:
            exception:
              title: Tümü
        header:
          display_link_grid:
            label: Izgara
          display_link_table:
            label: Tablo
    widget_table:
      display_options:
        fields:
          thumbnail__target_id:
            label: 'Küçük görsel'
          uid:
            label: Yazar
          changed:
            label: Güncellenme
        arguments:
          bundle:
            exception:
              title: Tümü
        header:
          display_link_grid:
            label: Izgara
          display_link_table:
            label: Tablo
