adding:
  remote_languages_mappings:
    en: EN
    ru: RU
    sq: ''
    al-sq: ''
    by-be: ''
    by-ru: RU
    bg-bg: BG
    gr-el: EL
    xk-sq: ''
    xk-rs: ''
    kg-ky: ''
    kg-ru: RU
    md-ro: RO
    me-cnr: ''
    mk-sq: ''
    mk-mk: ''
    ro: RO
    ro-ro: RO
    sr: ''
    rs-en: ''
    rs-sr: ''
    sk: SK
    tj-ru: RU
    tj-tg: ''
    uk: UK
    uz-ru: RU
    uz-uz: ''
    uz-kaa: ''
removing: {  }
