adding:
  display:
    default:
      display_options:
        fields:
          source_language:
            label: From
          operations:
            label: Operacionet
removing:
  display:
    default:
      display_options:
        fields:
          tags_count:
            label: Tags
          operations:
            label: Operations
