adding:
  display:
    default:
      display_options:
        fields:
          dropbutton:
            label: Operacionet
removing:
  display:
    default:
      display_options:
        fields:
          name:
            label: User
          group_roles:
            label: Roles
          dropbutton:
            label: Operations
