adding:
  label: Media
  display:
    default:
      display_options:
        title: Media
        fields:
          thumbnail__target_id:
            label: Thumbnail
    media_page_list:
      display_title: Media
      display_options:
        menu:
          title: Media
removing:
  label: Мультимедиа
  display:
    default:
      display_options:
        title: Мультимедиа
        fields:
          thumbnail__target_id:
            label: Миниатюра
            separator: ', '
          name:
            separator: ', '
          bundle:
            separator: ', '
          uid:
            label: Author
            separator: ', '
          status:
            label: Status
            separator: ', '
          changed:
            label: Updated
            separator: ', '
        pager:
          options:
            tags:
              next: 'Next ›'
              previous: '‹ Previous'
              first: '« First'
              last: 'Last »'
            expose:
              items_per_page_label: 'Items per page'
              items_per_page_options_all_label: '- All -'
              offset_label: Offset
        exposed_form:
          options:
            exposed_sorts_label: 'Sort by'
            sort_asc_label: Asc
            sort_desc_label: Desc
    media_page_list:
      display_title: Мультимедиа
      display_options:
        menu:
          title: Мультимедиа
