<?php

/**
 * @file
 * Primary hook implementations for the JSON Field module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function json_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the json_field module.
    case 'help.page.json_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a JSON field, formatter and views integration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function json_field_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_libraries_info().
 */
function json_field_libraries_info() {
  $libraries = [
    'jsonview' => [
      'name' => 'jsonview',
      'vendor url' => 'https://github.com/yesmeck/jquery-jsonview/releases',
      'download url' => 'https://github.com/yesmeck/jquery-jsonview/archive/v1.2.3.tar.gz',
      'files' => [
        'js' => [
          'dist/jquery.jsonview.js' => [],
        ],
        'css' => [
          'dist/jquery.jsonview.css' => [],
        ],
      ],
    ],
  ];
  return $libraries;
}
