name: Config Ignore
type: module
description: Ignore certain configuration during imports and exports
core_version_requirement: ^8.8 || ^9
package: Config
configure: config_ignore.settings

# Information added by Drupal.org packaging script on 2021-08-03
version: '8.x-3.0-beta1'
project: 'config_ignore'
datestamp: 1627977339
