adding:
  display:
    default:
      display_options:
        filters:
          flag_status:
            group_info:
              group_items:
                -
                  title: ''
                  value: ''
                -
                  title: ''
                  value: ''
                -
                  title: ''
                  operator: '='
                  value: ''
          countries_id:
            expose:
              label: 'Countries id'
        filter_groups:
          operator: AND
          groups:
            1: AND
        style:
          options:
            columns:
              country_id: country_id
            info:
              country_id:
                sortable: false
                default_sort_order: asc
                align: ''
                separator: ''
                empty_column: false
                responsive: ''
removing:
  display:
    default:
      display_options:
        filters:
          flag_status:
            group_info:
              group_items:
                -
                  title: Enable
                  value: '1'
                -
                  title: Disable
                  value: '0'
          countries_id:
            expose:
              label: 'Country Id'
        style:
          options:
            columns:
              countries_id: countries_id
            info:
              countries_id:
                sortable: false
                default_sort_order: asc
                align: ''
                separator: ''
                empty_column: false
                responsive: ''
