adding:
  channels:
    -
      id: purger_acquia_purge_d35096bddb
      grants:
        - 0
        - 2
    -
      id: purger_acquia_platform_cdn_c831dd8d95
    -
      id: diagnostics
removing:
  channels:
    -
      id: diagnostics
    -
      id: purger_acquia_purge_d35096bddb
    -
      id: purger_acquia_platform_cdn_c831dd8d95
      grants:
        - 0
        - 2
