adding:
  processor_configuration:
    langcode: en
  mappings:
    -
      settings:
        language: null
removing:
  processor_configuration:
    langcode: bg-bg
  mappings:
    -
      settings:
        language: bg-bg
