warmers:
  cdn:
    id: cdn
    frequency: 3600
    batchSize: 10
    urls:
      - '/api/activities/en'
      - '/api/archive/en'
      - '/api/articles/en'
      - '/api/articles/en?pregnancy=true'
      - '/api/basic-pages/en'
      - '/api/child-development-data/en'
      - '/api/child-growth-data/en'
      - '/api/daily-homescreen-messages/en'
      - '/api/faqs/en'
      - '/api/health-checkup-data/en'
      - '/api/milestones/en'
      - '/api/pinned-contents/en/child_development/40'
      - '/api/pinned-contents/en/child_development/41'
      - '/api/pinned-contents/en/child_growth'
      - '/api/pinned-contents/en/faq'
      - '/api/pinned-contents/en/health_check_ups'
      - '/api/pinned-contents/en/vaccinations'
      - '/api/related-article-contents/en/milestone'
      - '/api/standard_deviation/en'
      - '/api/surveys/en'
      - '/api/taxonomies/en/all'
      - '/api/updated-pinned-contents/en/faq'
      - '/api/vaccinations/en'
      - '/api/video-articles/en'
      - '/api/activities/fj-fj'
      - '/api/archive/fj-fj'
      - '/api/articles/fj-fj'
      - '/api/articles/fj-fj?pregnancy=true'
      - '/api/basic-pages/fj-fj'
      - '/api/child-development-data/fj-fj'
      - '/api/child-growth-data/fj-fj'
      - '/api/daily-homescreen-messages/fj-fj'
      - '/api/faqs/fj-fj'
      - '/api/health-checkup-data/fj-fj'
      - '/api/milestones/fj-fj'
      - '/api/pinned-contents/fj-fj/child_development/40'
      - '/api/pinned-contents/fj-fj/child_development/41'
      - '/api/pinned-contents/fj-fj/child_growth'
      - '/api/pinned-contents/fj-fj/faq'
      - '/api/pinned-contents/fj-fj/health_check_ups'
      - '/api/pinned-contents/fj-fj/vaccinations'
      - '/api/related-article-contents/fj-fj/milestone'
      - '/api/standard_deviation/fj-fj'
      - '/api/surveys/fj-fj'
      - '/api/taxonomies/fj-fj/all'
      - '/api/updated-pinned-contents/fj-fj/faq'
      - '/api/vaccinations/fj-fj'
      - '/api/video-articles/fj-fj'
      - '/api/activities/fj-en'
      - '/api/archive/fj-en'
      - '/api/articles/fj-en'
      - '/api/articles/fj-en?pregnancy=true'
      - '/api/basic-pages/fj-en'
      - '/api/child-development-data/fj-en'
      - '/api/child-growth-data/fj-en'
      - '/api/daily-homescreen-messages/fj-en'
      - '/api/faqs/fj-en'
      - '/api/health-checkup-data/fj-en'
      - '/api/milestones/fj-en'
      - '/api/pinned-contents/fj-en/child_development/40'
      - '/api/pinned-contents/fj-en/child_development/41'
      - '/api/pinned-contents/fj-en/child_growth'
      - '/api/pinned-contents/fj-en/faq'
      - '/api/pinned-contents/fj-en/health_check_ups'
      - '/api/pinned-contents/fj-en/vaccinations'
      - '/api/related-article-contents/fj-en/milestone'
      - '/api/standard_deviation/fj-en'
      - '/api/surveys/fj-en'
      - '/api/taxonomies/fj-en/all'
      - '/api/updated-pinned-contents/fj-en/faq'
      - '/api/vaccinations/fj-en'
      - '/api/video-articles/fj-en'
      - '/api/activities/ws-sm'
      - '/api/archive/ws-sm'
      - '/api/articles/ws-sm'
      - '/api/articles/ws-sm?pregnancy=true'
      - '/api/basic-pages/ws-sm'
      - '/api/child-development-data/ws-sm'
      - '/api/child-growth-data/ws-sm'
      - '/api/daily-homescreen-messages/ws-sm'
      - '/api/faqs/ws-sm'
      - '/api/health-checkup-data/ws-sm'
      - '/api/milestones/ws-sm'
      - '/api/pinned-contents/ws-sm/child_development/40'
      - '/api/pinned-contents/ws-sm/child_development/41'
      - '/api/pinned-contents/ws-sm/child_growth'
      - '/api/pinned-contents/ws-sm/faq'
      - '/api/pinned-contents/ws-sm/health_check_ups'
      - '/api/pinned-contents/ws-sm/vaccinations'
      - '/api/related-article-contents/ws-sm/milestone'
      - '/api/standard_deviation/ws-sm'
      - '/api/surveys/ws-sm'
      - '/api/taxonomies/ws-sm/all'
      - '/api/updated-pinned-contents/ws-sm/faq'
      - '/api/vaccinations/ws-sm'
      - '/api/video-articles/ws-sm'
      - '/api/activities/ws-en'
      - '/api/archive/ws-en'
      - '/api/articles/ws-en'
      - '/api/articles/ws-en?pregnancy=true'
      - '/api/basic-pages/ws-en'
      - '/api/child-development-data/ws-en'
      - '/api/child-growth-data/ws-en'
      - '/api/daily-homescreen-messages/ws-en'
      - '/api/faqs/ws-en'
      - '/api/health-checkup-data/ws-en'
      - '/api/milestones/ws-en'
      - '/api/pinned-contents/ws-en/child_development/40'
      - '/api/pinned-contents/ws-en/child_development/41'
      - '/api/pinned-contents/ws-en/child_growth'
      - '/api/pinned-contents/ws-en/faq'
      - '/api/pinned-contents/ws-en/health_check_ups'
      - '/api/pinned-contents/ws-en/vaccinations'
      - '/api/related-article-contents/ws-en/milestone'
      - '/api/standard_deviation/ws-en'
      - '/api/surveys/ws-en'
      - '/api/taxonomies/ws-en/all'
      - '/api/updated-pinned-contents/ws-en/faq'
      - '/api/vaccinations/ws-en'
      - '/api/video-articles/ws-en'
    headers: {  }
    verify: true
    maxConcurrentRequests: 2
