adding:
  dependencies:
    config:
      - media.type.image
      - media.type.remote_video
      - media.type.video
      - node.type.vaccinations
    module:
      - actions_permissions
      - allowed_languages
      - content_translation
      - file
      - group
      - media
      - tmgmt
  permissions:
    - 'accept translation jobs'
    - 'access media overview'
    - 'access user profiles'
    - 'administer allowed languages'
    - 'bypass group access'
    - 'create content translations'
    - 'create media'
    - 'create vaccinations content'
    - 'delete own files'
    - 'edit own image media'
    - 'edit own remote_video media'
    - 'edit own video media'
    - 'execute pb_custom_field_assign_action node'
    - 'translate all languages'
    - 'translate any entity'
    - 'translate image media'
    - 'translate remote_video media'
    - 'translate video media'
    - 'update any media'
    - 'update content translations'
    - 'update media'
    - 'view all media revisions'
removing: {  }
