adding:
  fetcher_configuration:
    directory: 'public://feeds'
  processor_configuration:
    langcode: ec-es
    insert_new: 1
    update_existing: 1
    update_non_existent: 'entity:unpublish_action:taxonomy_term'
  mappings:
    -
      settings:
        language: ec-es
removing:
  fetcher_configuration:
    directory: 'private://feeds'
  processor_configuration:
    langcode: uz-kaa
    insert_new: 0
    update_existing: 2
    update_non_existent: _keep
  mappings:
    -
      settings:
        language: uz-kaa
