adding:
  settings:
    allowed_values:
      -
        value: Wawamor
        label: Wawamor
removing:
  settings:
    allowed_values:
      -
        value: Bebbo
        label: Bebbo
      -
        value: Foleja
        label: Foleja
