adding:
  content:
    created:
      weight: 19
    field_australian_article:
      weight: 15
    field_cover_video:
      weight: 9
    field_licensed_content:
      weight: 13
    field_mandatory_content:
      weight: 17
    field_meta_keywords:
      weight: 8
    field_premature_content:
      weight: 14
    field_references_and_comments:
      weight: 16
    field_related_articles:
      weight: 10
    field_related_video_articles:
      weight: 11
    moderation_state:
      weight: 24
    path:
      weight: 22
    promote:
      weight: 20
    status:
      weight: 23
    sticky:
      weight: 21
    translation:
      weight: 12
    uid:
      weight: 18
removing:
  content:
    created:
      weight: 18
    field_australian_article:
      weight: 14
    field_cover_video:
      weight: 8
    field_licensed_content:
      weight: 12
    field_mandatory_content:
      weight: 16
    field_meta_keywords:
      weight: 28
    field_premature_content:
      weight: 13
    field_references_and_comments:
      weight: 15
    field_related_articles:
      weight: 9
    field_related_video_articles:
      weight: 10
    moderation_state:
      weight: 23
    path:
      weight: 21
    promote:
      weight: 19
    status:
      weight: 22
    sticky:
      weight: 20
    translation:
      weight: 11
    uid:
      weight: 17
