warmers:
  cdn:
    id: cdn
    frequency: 3600
    batchSize: 10
    urls:
      - '/api/activities/es'
      - '/api/archive/es'
      - '/api/articles/es'
      - '/api/articles/es?pregnancy=true'
      - '/api/basic-pages/es'
      - '/api/child-development-data/es'
      - '/api/child-growth-data/es'
      - '/api/daily-homescreen-messages/es'
      - '/api/faqs/es'
      - '/api/health-checkup-data/es'
      - '/api/milestones/es'
      - '/api/pinned-contents/es/child_development/40'
      - '/api/pinned-contents/es/child_development/41'
      - '/api/pinned-contents/es/child_growth'
      - '/api/pinned-contents/es/faq'
      - '/api/pinned-contents/es/health_check_ups'
      - '/api/pinned-contents/es/vaccinations'
      - '/api/related-article-contents/es/milestone'
      - '/api/standard_deviation/es'
      - '/api/surveys/es'
      - '/api/taxonomies/es/all'
      - '/api/updated-pinned-contents/es/faq'
      - '/api/vaccinations/es'
      - '/api/video-articles/es'
      - '/api/activities/ec-es'
      - '/api/archive/ec-es'
      - '/api/articles/ec-es'
      - '/api/articles/ec-es?pregnancy=true'
      - '/api/basic-pages/ec-es'
      - '/api/child-development-data/ec-es'
      - '/api/child-growth-data/ec-es'
      - '/api/daily-homescreen-messages/ec-es'
      - '/api/faqs/ec-es'
      - '/api/health-checkup-data/ec-es'
      - '/api/milestones/ec-es'
      - '/api/pinned-contents/ec-es/child_development/40'
      - '/api/pinned-contents/ec-es/child_development/41'
      - '/api/pinned-contents/ec-es/child_growth'
      - '/api/pinned-contents/ec-es/faq'
      - '/api/pinned-contents/ec-es/health_check_ups'
      - '/api/pinned-contents/ec-es/vaccinations'
      - '/api/related-article-contents/ec-es/milestone'
      - '/api/standard_deviation/ec-es'
      - '/api/surveys/ec-es'
      - '/api/taxonomies/ec-es/all'
      - '/api/updated-pinned-contents/ec-es/faq'
      - '/api/vaccinations/ec-es'
      - '/api/video-articles/ec-es'
    headers:
      - 'X-Bebbo-Warmer: 1'
    verify: true
    maxConcurrentRequests: 8
