<?php

/**
 * @file
 * It contains custom field module.
 */

/**
 * Implements hook_theme().
 */
function pb_custom_form_theme($existing, $type, $theme, $path) {
  $config = \Drupal::config('pb_custom_form.mobile_app_share_link_form');

  return [
    'pb-mobile' => [
      'variables' => ['app_share_script' => $config->get('mobile_app_share_link')],
    ],
  ];
}

// function pb_custom_form_create_custom_menu()
// {

//     $menu = array();
//     $menu['menu_name'] = "parent_buddy";
//     $menu['title'] = "Parent Buddy";
//     $menu['description'] = "The <em>Parent Buddy</em> menu contains custom form links";
//     menu_save($menu);

// }