adding:
  settings:
    allowed_values:
      -
        value: Babuni
        label: Babuni
removing:
  settings:
    allowed_values:
      -
        value: Bebbo
        label: Bebbo
      -
        value: Foleja
        label: Foleja
