adding:
  dependencies:
    config:
      - field.field.group.country.field_app_name
      - field.field.group.country.field_language_name_in_local
      - field.field.group.country.field_language_visibility_in_app
  content:
    field_app_name:
      type: options_select
      weight: 1
      region: content
  hidden:
    field_language_name_in_local: true
    field_language_visibility_in_app: true
removing: {  }
