adding:
  status: true
  dependencies:
    config:
      - field.storage.node.field_do_not_feature
      - field.storage.node.field_meta_keywords
      - field.storage.node.field_subcategory
      - field.storage.node.field_type_of_article
    content:
      - 'taxonomy_term:child_age:04fd7356-7d87-48cc-90c8-c1e279d6c0e0'
      - 'taxonomy_term:child_age:18f97ba2-6aaa-4bf9-b091-6bb14ececff4'
      - 'taxonomy_term:child_age:1da80bce-47e0-4d1c-8309-281d7a107a16'
      - 'taxonomy_term:child_age:670f8241-f5ab-4ab7-9440-c233857ee87b'
      - 'taxonomy_term:child_age:68e9248d-4f86-4e66-b8a8-baeb2e2a09b9'
      - 'taxonomy_term:child_age:96d4e260-9c9c-43d1-9b72-22efa38f0e7c'
      - 'taxonomy_term:child_age:c47cbe38-eba4-4f60-9a83-ac210b677c27'
      - 'taxonomy_term:child_age:d2de49df-f3ec-4c18-b8ee-f3da74a640dd'
      - 'taxonomy_term:child_age:eea0f4de-3d5b-497b-aae0-c89714320ba5'
      - 'taxonomy_term:child_age:f61ab0d4-4be0-4aaf-a659-310e26dd0f95'
      - 'taxonomy_term:child_age:f63598f6-595e-4fa4-bb98-89ac751f0db9'
      - 'taxonomy_term:child_age:f8ab9faf-82cd-410f-9cbf-b360ba9316a3'
  display:
    rest_export_2:
      display_options:
        fields:
          field_type_of_article:
            id: field_type_of_article
            table: node__field_type_of_article
            field: field_type_of_article
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: target_id
            type: entity_reference_entity_id
            settings: {  }
            group_column: target_id
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          field_subcategory:
            id: field_subcategory
            table: node__field_subcategory
            field: field_subcategory
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: target_id
            type: entity_reference_entity_id
            settings: {  }
            group_column: target_id
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          field_meta_keywords:
            id: field_meta_keywords
            table: node__field_meta_keywords
            field: field_meta_keywords
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: basic_string
            settings: {  }
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
          field_do_not_feature:
            id: field_do_not_feature
            table: node__field_do_not_feature
            field: field_do_not_feature
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: ''
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: false
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: value
            type: boolean
            settings:
              format: boolean
              format_custom_false: ''
              format_custom_true: ''
            group_column: value
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
removing:
  status: false
  dependencies:
    content:
      - 'taxonomy_term:growth_period:b39dfd70-bcb3-492a-848c-aacc7cdc3f35'
      - 'taxonomy_term:growth_period:dbc44001-5cb3-4321-81c9-3474a1a89961'
