adding:
  dependencies:
    config:
      - user.role.administrator
      - user.role.anonymous
      - user.role.authenticated
      - user.role.editor
      - user.role.global_admin
      - user.role.reviewer
      - user.role.se
      - user.role.sme
  display:
    default:
      display_options:
        access:
          type: role
          options:
            role:
              anonymous: anonymous
              authenticated: authenticated
              global_admin: global_admin
              reviewer: reviewer
              editor: editor
              sme: sme
              se: se
              administrator: administrator
      cache_metadata:
        contexts:
          - user.roles
removing:
  display:
    default:
      display_options:
        access:
          type: perm
          options:
            perm: 'access content'
      cache_metadata:
        contexts:
          - user.permissions
