adding:
  uuid: 97e2fae4-d052-48b4-befb-90299b5db751
  langcode: tr
  label: 'Türkiye - Turkish'
  weight: 9
removing:
  uuid: 0f60408b-0472-4aa4-9014-f82d6fc80c65
  langcode: en
  label: Turkish
  weight: 13
