adding:
  url:
    prefixes:
      gr-arb: gr-arb
      gr-fa: gr-fa
      ar: ar
      bn: bn
    domains:
      gr-arb: ''
      gr-fa: ''
      ar: ''
      bn: ''
removing:
  url:
    prefixes:
      uz-kaa: uz-kaa
    domains:
      uz-kaa: ''
