appID: 87664ZTMV3.org.unicef.bangladesh.babuni
paths: '/share/*'
appclips: ''
appID_Test: ''
paths_Test: ''
kosovo_appID: ''
kosovo_paths: ''
kosovo_appclips: ''
kosovo_appID_Test: ''
kosovo_paths_Test: ''
applinks:
  87664ZTMV3-org-unicef-bangladesh-babuni_0:
    applinks: ''
    appID: 87664ZTMV3.org.unicef.bangladesh.babuni
    paths: '/share/*'
    appclips: ''
    appIDs: {  }
    defaults: ''
