warmers:
  cdn:
    id: cdn
    frequency: 3600
    batchSize: 10
    urls:
      - '/api/activities/bn'
      - '/api/archive/bn'
      - '/api/articles/bn'
      - '/api/articles/bn?pregnancy=true'
      - '/api/basic-pages/bn'
      - '/api/child-development-data/bn'
      - '/api/child-growth-data/bn'
      - '/api/daily-homescreen-messages/bn'
      - '/api/faqs/bn'
      - '/api/health-checkup-data/bn'
      - '/api/milestones/bn'
      - '/api/pinned-contents/bn/child_development/40'
      - '/api/pinned-contents/bn/child_development/41'
      - '/api/pinned-contents/bn/child_growth'
      - '/api/pinned-contents/bn/faq'
      - '/api/pinned-contents/bn/health_check_ups'
      - '/api/pinned-contents/bn/vaccinations'
      - '/api/related-article-contents/bn/milestone'
      - '/api/standard_deviation/bn'
      - '/api/surveys/bn'
      - '/api/taxonomies/bn/all'
      - '/api/updated-pinned-contents/bn/faq'
      - '/api/vaccinations/bn'
      - '/api/video-articles/bn'
    headers:
      - 'X-Bebbo-Warmer: 1'
    verify: true
    maxConcurrentRequests: 8
