adding:
  display:
    default:
      display_options:
        fields:
          created:
            label: Created
        arguments:
          tjid:
            exception:
              title: All
removing:
  display:
    default:
      display_title: Master
      display_options:
        exposed_form:
          options:
            submit_button: Použiť
            exposed_sorts_label: 'Zoradiť podľa'
            sort_asc_label: Vzostupne
            sort_desc_label: Zostupne
        pager:
          options:
            tags:
              previous: '‹ predchádzajúca'
              next: 'nasledujúca ›'
              first: '« prvá'
              last: 'posledná »'
            expose:
              items_per_page_label: 'Položky na stránku'
              items_per_page_options_all_label: '- Všetky -'
              offset_label: Ofset
        fields:
          created:
            label: Vytvorené
          label:
            label: Položka
          name:
            separator: ', '
        title: Správy
        arguments:
          tjid:
            exception:
              title: Všetko
    embed:
      display_title: Vložiť
