label: Përmbajtja
display:
  default:
    display_title: Default
    display_options:
      title: Përmbajtja
      fields:
        title:
          label: Title
        name:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Publikuar
        langcode:
          label: Language
        operations:
          label: Operations
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
      filters:
        title:
          expose:
            label: Title
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Publikuar
        langcode:
          expose:
            label: Language
  page_1:
    display_title: Faqe
    display_options:
      menu:
        title: Përmbajtja
      tab_options:
        title: Përmbajtja
