display:
  default:
    display_options:
      fields:
        edit_user:
          text: 'Edit member'
        name:
          label: User
        group_roles:
          label: Roles
        view_group_relationship:
          text: 'Manage member'
        edit_group_relationship:
          text: 'Assign roles'
        dropbutton:
          label: Operations
      exposed_form:
        options:
          reset_button_label: Reset
      arguments:
        gid:
          exception:
            title: All
  page_1:
    display_title: Faqe
