display:
  default:
    display_title: Default
    display_options:
      fields:
        title:
          label: Title
        name:
          label: Author
      exposed_form:
        options:
          reset_button_label: Reset
  page_1:
    display_title: Faqe
