tmgmt_content.settings:
  type: config_entity
  mapping:
    embedded_fields:
      label: 'Embedded fields'
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: boolean
    default_moderation_states:
      label: 'Default moderation states'
      type: sequence
      sequence:
        type: string

field.field.*.*.*.third_party.tmgmt_content:
  type: mapping
  label: 'Content Entity Source field settings'
  mapping:
    excluded:
      type: boolean
      label: 'Exclude field from translation'
