adding:
  display:
    default:
      display_options:
        fields:
          created:
            label: 'Yüklenme tarihi'
removing:
  display:
    default:
      display_options:
        fields:
          fid:
            label: Fid
          filename:
            separator: ', '
