adding: {  }
removing:
  display:
    default:
      display_options:
        pager:
          options:
            tags:
              next: ››
              previous: ‹‹
        arguments:
          created_year_month:
            title: '{{ arguments.created_year_month }}'
    block_1:
      display_options:
        arguments:
          created_year_month:
            title: '{{ arguments.created_year_month }}'
