warmers:
  cdn:
    id: cdn
    frequency: 3600
    batchSize: 10
    urls:
      - '/api/activities/en'
      - '/api/archive/en'
      - '/api/articles/en'
      - '/api/articles/en?pregnancy=true'
      - '/api/basic-pages/en'
      - '/api/child-development-data/en'
      - '/api/child-growth-data/en'
      - '/api/daily-homescreen-messages/en'
      - '/api/faqs/en'
      - '/api/health-checkup-data/en'
      - '/api/milestones/en'
      - '/api/pinned-contents/en/child_development/40'
      - '/api/pinned-contents/en/child_development/41'
      - '/api/pinned-contents/en/child_growth'
      - '/api/pinned-contents/en/faq'
      - '/api/pinned-contents/en/health_check_ups'
      - '/api/pinned-contents/en/vaccinations'
      - '/api/related-article-contents/en/milestone'
      - '/api/standard_deviation/en'
      - '/api/surveys/en'
      - '/api/taxonomies/en/all'
      - '/api/updated-pinned-contents/en/faq'
      - '/api/vaccinations/en'
      - '/api/video-articles/en'
      - '/api/activities/ur'
      - '/api/archive/ur'
      - '/api/articles/ur'
      - '/api/articles/ur?pregnancy=true'
      - '/api/basic-pages/ur'
      - '/api/child-development-data/ur'
      - '/api/child-growth-data/ur'
      - '/api/daily-homescreen-messages/ur'
      - '/api/faqs/ur'
      - '/api/health-checkup-data/ur'
      - '/api/milestones/ur'
      - '/api/pinned-contents/ur/child_development/40'
      - '/api/pinned-contents/ur/child_development/41'
      - '/api/pinned-contents/ur/child_growth'
      - '/api/pinned-contents/ur/faq'
      - '/api/pinned-contents/ur/health_check_ups'
      - '/api/pinned-contents/ur/vaccinations'
      - '/api/related-article-contents/ur/milestone'
      - '/api/standard_deviation/ur'
      - '/api/surveys/ur'
      - '/api/taxonomies/ur/all'
      - '/api/updated-pinned-contents/ur/faq'
      - '/api/vaccinations/ur'
      - '/api/video-articles/ur'
    headers: {  }
    verify: true
    maxConcurrentRequests: 2
