<?php

/**
 * @file
 * Contains title_length.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Site\Settings;

define('TITLE_LENGTH_CHARS', 500);

/**
 * Implements hook_entity_base_field_info_alter().
 */
function title_length_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  // Alter the title field to change length.
  if (!empty($fields['title']) && $entity_type->id() === 'node') {
    // Get length of settings.
    $length = Settings::get('node_title_length_chars') ?: TITLE_LENGTH_CHARS;
    $fields['title']->setSetting('max_length', $length);
  }
}
